### ISSUE TITLE
feature: bork wipe command

### ISSUE THREAD

**Issue by arnm** [mattly/bork#130]
I am looking for the opposite of the command `bork satisfy` which would "wipe" anything which is declared in the configuration. Delete any repos, symlinks, remove installed applications, etc.

Bork makes it easy to get a system looking how you want but it does not make it easy to revert any changes you've made.

**Comment by timuckun** [comment]
In addition I think a "nok, 'not", "not_ok"  command would be useful as in "remove this package" or "remove this file"

**Comment by mattly** [comment]
So I've specifically had the idea of a `not_ok` directive – that is, an individual assertion that appears in a config file. I'm not entirely sure how useful it would be, but it at least fits into the notion of what the config is. And inverting an `ok` in satisfy is theoretically simple.

On the other hand, inverting `satisfy` gets into I feel dangerous territory. There is really only one assertion right now – `ok`, and it fits into this notion, but what would `bork unsatifsy` do with say, `not_ok brew bash` ? make sure it's installed?

Finally, there's the matter of side-effects. I have, as much as possible, tried to make bork itself side-effect free where practical. But the things it interfaces with are often-times not practical to do that. So if I have `ok brew clojure`, that installs java. A `bork wipe` *could* remove clojure, but it *could not* remove java without a lot of work that for some interfaces might not even be possible. But the thing of it is, I would expect it to remove java. After all, it was installed via bork, right?

In any regard, I've neither time nor interest in building such a thing myself. If someone is serious about building it, let's talk and make sure we're on the same page with regard to how it works.
