### ISSUE TITLE
Improve BORK_SOURCE_DIR so bork can be executed via a symlink

### ISSUE THREAD

**Issue by frdmn** [mattly/bork#54]
I'm trying to create a Homebrew formula for bork, but at the moment I'm stuck since bork, doesnt like to be executed when symlinked:

```shell
❯  ~  ls -la /usr/local/bin/bork
lrwxr-xr-x  1 jonas  staff  31 23 Mär 14:03 /usr/local/bin/bork -> ../Cellar/bork/a885baa/bin/bork
❯  ~  bork
/usr/local/bin/bork: line 32: /usr/local/Cellar/bork/a885baa/bin/bork/lib/helpers/*.sh: Not a directory
/usr/local/bin/bork: line 32: /usr/local/Cellar/bork/a885baa/bin/bork/lib/declarations/*.sh: Not a directory
bork usage:
```

Perhaps you could adjust it so it returns the actual location instead of location of the symlink.

While testing around a bit, I've found out that `$(realpath $0)` returns the expected path, but that binary doesn't come with OS X by default. (`coreutils` brew package).

Any ideas how to solve this?

**Comment by diffsky** [comment]
@mattly you might find this bit of code useful for resolving the true file:
https://github.com/diffsky/bolt/blob/master/bin/bolt#L3-L10

**Comment by mattly** [comment]
My plan was to actually have bork compile itself with some markers so it knew which parts to pull out for compiling, but this is probably easier. :) And it'll work with homebrew too. :)

So I had a hit list for a proper release but eh, I can throw that out the window and at least get *something* up. I'm guessing we need version number tags or something for homebrew?

**Comment by mattly** [comment]
Fixed by fd49cab22c2c0b49f1652771d2f0ee4687212a2e ...I hope.

Thanks @frdmn for bringing the problem to my attention and @diffsky for providing a pointer to a solution.

**Comment by mattly** [comment]
I went ahead and tagged the fixed version as "v0.9". There's a release up on the releases tab.

**Comment by frdmn** [comment]
@mattly Perfect! Filed the PR including the new formula: https://github.com/Homebrew/homebrew/pull/50382

**Comment by frdmn** [comment]
@mattly Just noticed a little issue when trying to exectute the following:

```shell
bork satisfy /Users/jonas/.dotfiles/borkfiles/atom.bork
/usr/local/bin/bork: line 28: cd: /Users/jonas//Users/jonas/.dotfiles/borkfiles/..: No such file or directory
ok: directory /Users/jonas/.atom
ok: symlink /Users/jonas/.atom/config.cson /Users/jonas/.dotfiles/opt/config.cson
ok: apm atom-beautify
ok: apm autocomplete-paths
ok: apm color-picker
ok: apm docblockr
ok: apm file-icons
ok: apm file-types
ok: apm hashrocket
ok: apm hex
ok: apm highlight-line
ok: apm jquery-snippets
ok: apm linter
ok: apm linter-htmlhint
ok: apm linter-jshint
ok: apm linter-jsonlint
ok: apm linter-php
ok: apm linter-shellcheck
ok: apm minimap
ok: apm minimap-git-diff
ok: apm pigments
ok: apm quantum-syntax
ok: apm quantum-ui
ok: apm script
ok: apm sort-lines
ok: apm tasks
ok: apm the-closer
ok: apm valign
```

I assume that's because of the change which happened in fd49cab22c2c0b49f1652771d2f0ee4687212a2e

**Comment by mattly** [comment]
harumph. I'll see what I can figure out. Also, you wrote an APM type?

**Comment by mattly** [comment]
ok, I think I've got it now. I've never passed in an absolute path on the command line before, it assumed a relative path. I cut a new release as well.

**Comment by frdmn** [comment]
Just woke up and giving it a spin in some minutes. Regarding the `apm` type: It's not really a bork compatible type yet, more of a script that's executed by my dotfile wrapper: https://github.com/frdmn/dotfiles/blob/master/borkfiles/atom.bork

I've planned to turn this into a proper bork type at some point but I switched (onec again) from Atom to Sublime Text so I don't have that much incentive for me at the moment.

**Comment by mattly** [comment]
ok, great. let me know how this works for you and I'll close the issue.

Fixing this actually helped me find a problem with the `destination` utility and how it works with `ok`. I wanted to get rid of `destination` anyway, now it looks like I've got an excuse.

**Comment by frdmn** [comment]
Problem fixed, thanks @mattly!
