### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by bcomnes** [mattly/bork#70]
It would be nice if the output of `satisfy` could be colorized based on the results: e.g. green for good/ok, yellow for upgradable/work, red for failed or conflict.

**Comment by mattly** [comment]
believe me, I've got a whole slew of improvements I'd like to make to the output.

**Comment by rnarian** [comment]
😎 👍

**Comment by bcomnes** [comment]
Ok I'll close this until there is more to talk about.
