### ISSUE TITLE
IRC Channel?

### ISSUE THREAD

**Issue by bcomnes** [mattly/bork#77]
It didn't look like this project had an IRC channel yet.  I grabbed #bork.sh on freenode if anyone else wants to join.   (#bork was taken already, although we probably have precedence to take it due to freenode rules... but thats disruptive)

@mattly how do you feel about endorsing an IRC channel in the readme ?

**Comment by frdmn** [comment]
Love the idea, since I use IRC daily!

---

Feel free to join us:

- Hostname: `irc.freenode.org`
- Channel: `#bork.sh`
- [Webmail client in case you don't have a native one](http://webchat.freenode.net?channels=%23bork.sh&uio=d4)

**Comment by mattly** [comment]
Thanks! Sorry for the non-responsiveness, my wife and I just had our first child and things have been a bit crazy around here lately.

@frdmn I'm going to give you commit rights, if you want to tackle readme updates and the like.

**Comment by frdmn** [comment]
Sounds good! 👍

**Comment by bcomnes** [comment]
@mattly Oh man, I had no idea!

Totally focus on whats important and no need to apologies 👍 @frdmn and I can work on small stuff.
