### ISSUE TITLE
brew-tap's install action, doesn't actually update taps

### ISSUE THREAD

**Issue by frdmn** [mattly/bork#78]
Just noticed that `bork do ok brew-tap <tap>` doesn't actually update the (indeed outdated) tap:

```
❯ bork do ok brew-tap frdmn/formulas
ok: brew-tap frdmn/formulas
```

According to the Homebrew docs, the `brew update` command is used to update them.

Can someone double check and maybe confirm this bug?

**Comment by mattly** [comment]
I think this is actually the intended behavior, as the `ok brew-tap some/tap` statement represents "have you added the tap or not, and is it pinned or not?", and it doesn't seem homebrew offers a way to keep taps updated individually outside of the all-at-once update of `brew update`. It does seem a bit counterintuitive, so I will add some info to the docs about that.
