### ISSUE TITLE
homebrew 1.0 has a few changes

### ISSUE THREAD

**Issue by mattly** [mattly/bork#83]
1. the repository moved to `/usr/local/Homebrew`, though really we should check against `brew config | grep HOMEBREW_REPOSITORY` and perhaps fall back to `/usr/local`
2. brew auto-updates itself whenever it installs anything. While I understand why, this is not ideal. Maybe there's a way to override that behavior?

**Comment by mattly** [comment]
From the man page

```
HOMEBREW_NO_AUTO_UPDATE
              If set, Homebrew will not auto-update before running brew install, brew upgrade or brew tap.
```

**Comment by edrex** [comment]
Related, I think:

```
❯ bork do ok brew
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
ok: brew
```

**Comment by frdmn** [comment]
@edrex Would you do me a favour and try PR #88?
