### ISSUE TITLE
New v0.X.0/v0.10.1 Release?

### ISSUE THREAD

**Issue by alfiepates** [mattly/bork#95]
The Homebrew package for Bork is based off the v0.10.0 release from March 2016, which is missing a lot of the newer fixes including PR #88 which is fairly essential if you're installing through Homebrew. 

Whilst it *is* possible to install with `brew install --HEAD`, it's not best practice by any means, and prevents automatically updating via the `brew upgrade`: Therefore it'd be helpful to have a versioned release with recent (stable) changes which can be packaged as usual.

**Comment by alfiepates** [comment]
I'd also like to see PR #94 included in this, actually; `brew cask` has had a few changes which broke compatibility with the old `cask` type.

**Comment by mattly** [comment]
I'm going to take a stab at this this weekend.

**Comment by mattly** [comment]
See #120. My plan is to merge, tag, & submit a PR to homebrew this evening.

**Comment by alfiepates** [comment]
Awesome. Looking forward to running a proper release version instead of  
HEAD again!

**Comment by mattly** [comment]
ok, we have a proper tag with resultant tarball, and an update in homebrew

```
Updated Homebrew from d558ec093 to 9b2610b0a.
Updated 2 taps (homebrew/core, caskroom/cask).
==> Updated Formulae
bork ✔
```
